// Boards Action for datas
export const ADD_ITEM = 'ADD_ITEM'
export const EDIT_ITEM = 'EDIT_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const ADD_CONTAINER = 'ADD_CONTAINER'
export const EDIT_CONTAINER = 'EDIT_CONTAINER'
export const DELETE_CONTAINER = 'DELETE_CONTAINER'
export const CHANGE_ITEM_POSITION_IN_SAME_CONTAINER =
  'CHANGE_ITEM_POSITION_IN_SAME_CONTAINER'
export const CHNAGE_ITEM_POSITION_IN_DIFFERNT_CONTAINER =
  'CHNAGE_ITEM_POSITION_IN_DIFFERNT_CONTAINER'
export const CHANGE_COLUMN = 'CHANGE_COLUMN'
export const ADD_BOARD = 'ADD_BOARD'
export const EDIT_BOARD = 'EDIT_BOARD'
export const DELETE_BOARD = 'DELETE_BOARD'
export const SET_BOARDS = 'SET_BOARDS'
export const SET_COLUMNS = 'SET_COLUMNS'

// Fetch Data Actions
export const FETCH_MYBOARDS = 'FETCH_MYBOARDS'
export const FETCH_INDIVIDUAL_BOARD = 'FETCH_INDIVIDUAL_BOARD'

// member
export const ADD_MEMBER_IN_BOARD = 'ADD_MEMBER_IN_BOARD'
export const REMOVE_MEMBER_IN_BOARD = 'REMOVE_MEMBER_IN_BOARD'

export const SET_INITIAL_STATE_FETCH_REDUCER = 'SET_INITIAL_STATE_FETCH_REDUCER'

export const SET_INITIAL_STATE_BOARD_REDUCER = 'SET_INITIAL_STATE_BOARD_REDUCER'
